name: json_converter_generator
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  build: ^2.3.1
  source_gen: ^1.2.7
  json_converter_generator_annotation: ^0.0.1
  analyzer: ^5.4.0
  build_config: '>=0.4.4 <2.0.0'

dev_dependencies:
  build_runner: ^2.1.4
  build_test: ^2.1.0
  flutter_lints: ^2.0.0
