targets:
  $default:
    builders:
      freezed:
        options:
          runs_before: ["json_serializable|json_serializable", "objectbox_generator|resolver", "objectbox_generator|generator"]
      json_serializable:
        options:
          explicit_to_json: true