name: post_reader_demo
description: A post reader using freezed, retrofit and objectbox
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  retrofit: ^4.0.1
  dio: ^5.1.0
  path_provider: ^2.0.5
  path: ^1.8.0
  objectbox: ^2.0.0
  objectbox_flutter_libs: ^2.0.0
  freezed_annotation: ^2.2.0
  json_converter_generator_annotation: ^0.0.1
  json_annotation: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  retrofit_generator: ^6.0.0+1
  json_serializable: ^6.6.1
  build_runner: ^2.3.3
  objectbox_generator: ^2.0.0
  json_converter_generator: ^0.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/post_comments.json
